services:   
    analytics.generate.factory:
        class: AnalyticsBundle\Generate\GenerateFactory
        arguments: [@service_container]
        
    analytics.generate:
        class: AnalyticsBundle\Generate\Generate
    
    analytics.analysis:
        class: AnalyticsBundle\Analysis\Analysis
        
    analytics.click_analysis:
        class: AnalyticsBundle\Analysis\ClickAnalysis
        arguments: [@service_container]