services:   
    analytics.generate.factory:
        class: AnalyticsBundle\Generate\GenerateFactory
        arguments: [@service_container]
        
    analytics.generate:
        class: AnalyticsBundle\Generate\Generate
    
    analytics.analysis:
        class: AnalyticsBundle\Analysis\Analysis
        
    analytics.click_analysis:
        class: AnalyticsBundle\Analysis\ClickAnalysis
        arguments: [@service_container]
        
    analytics.command.test:
        class: AnalyticsBundle\Command\LoadCronTaskData
        arguments: [@service_container]
        
    doctrine.listener.pre_persist_redirection_generate:
        class: AnalyticsBundle\EventListener\RedirectionGenerateListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }