#imports:
#    - { resource: '@SonataTranslationBundle/Resources/config/config.yml'}

sonata_translation:
    locales: [pl, fr, en, it, nl, es]
    default_locale: pl
    # here enable the types you need
    gedmo:
        enabled: true
    phpcr:
        enabled: false
