parameters:
    # ... other parameters
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap
    # optionally use a custom MaskBuilder
    #sonata.admin.security.mask.builder.class: Sonata\AdminBundle\Security\Acl\Permission\MaskBuilder

services:
    sonata.admin.campaign:
        class: AnalyticsBundle\Admin\CampaignAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Campaign" }
        arguments:
            - ~
            - AnalyticsBundle\Entity\Campaign
            - ~
        calls:
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
            
    sonata.admin.redirection:
        class: AnalyticsBundle\Admin\RedirectionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Redirection" }
        arguments:
            - ~
            - AnalyticsBundle\Entity\Redirection
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
            
    sonata.admin.click:
        class: AnalyticsBundle\Admin\ClickAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Click" }
        arguments:
            - ~
            - AnalyticsBundle\Entity\Click
            - ~
        calls:
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
            
    sonata.admin.redirection_statistic_click:
        class: AnalyticsBundle\Admin\RedirectionStatisticAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "RedirectionStatistic" }
        arguments:
            - ~
            - AnalyticsBundle\Entity\RedirectionStatistic
            - ~
        calls:
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
            
    sonata.block.statistic_clicks:
        class: AnalyticsBundle\Block\StatisticClicksBlockService
        tags:
            - { name: sonata.block }
        arguments: ['sonata.block.statistic_clicks', '@templating']