<?php

namespace AnalyticsBundle\Repository;

use AnalyticsBundle\Repository\EntityRepository;
use AnalyticsBundle\Entity\RedirectionStatistic;

/**
 * RedirectionStatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectionStatisticRepository extends EntityRepository {

    public function create($params) {

        $redirectionStatistic = new RedirectionStatistic();

        $redirectionStatistic->setRedirectUrlId($params['redirectUrlId']);
        $redirectionStatistic->setClickCount($params['clickCount']);
        $redirectionStatistic->setDate($params['date']);
        
        return $redirectionStatistic;
    }
    
    public function update($entity, $params){
        
//        $entity->setRedirectUrlId($params['redirectUrlId']);
        $entity->setClickCount($params['clickCount']);
        $entity->setDate($params['date']);
        
        return $entity;
    }
}
