<?php

namespace AnalyticsBundle\Repository;

use AnalyticsBundle\Repository\EntityRepository;

/**
 * RedirectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectionRepository extends EntityRepository
{
}