<?php

namespace AnalyticsBundle\Repository;

use AnalyticsBundle\Repository\EntityRepository;
use AnalyticsBundle\Entity\Redirection;

/**
 * RedirectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectionRepository extends EntityRepository 
{
    public function create($params) {

        $redirection = new Redirection();

        $redirection->setUserId($params['userId']);
        $redirection->setOriginUrl($params['originUrl']);
        $redirection->setGeneratedUrl($params['generatedUrl']);

        return $redirection;
    }
    
    public function findEntity($entityName, $entityId) {
//        return $this->repository->findEntity($entityName, $entityId);
    }
}
